In [46]:
import pandas as pd 
import time
import random
import os
from datetime import datetime
import uuid

In [47]:
url = ['https://www.espn.com.co/futbol/posiciones/_/liga/esp.1',
      'https://www.espn.com.co/futbol/posiciones/_/liga/eng.1',
      'https://www.espn.com.co/futbol/posiciones/_/liga/ita.1',
      'https://www.espn.com.co/futbol/posiciones/_/liga/ger.1',
      'https://www.espn.com.co/futbol/posiciones/_/liga/fra.1',
      'https://www.espn.com.co/futbol/posiciones/_/liga/por.1',
      'https://www.espn.com.co/futbol/posiciones/_/liga/ned.1']
ligas = ['ESPAÑA','INGLATERRA','ITALIA','GERMANY','FRANCIA','PORTUGAL','HOLANDA']

df_ligas = {
    'LIGA':ligas,
    'URL':url
} 

df_ligas = pd.DataFrame(df_ligas)
df_ligas

         LIGA                                                URL
0      ESPAÑA  https://www.espn.com.co/futbol/posiciones/_/li...
1  INGLATERRA  https://www.espn.com.co/futbol/posiciones/_/li...
2      ITALIA  https://www.espn.com.co/futbol/posiciones/_/li...
3     GERMANY  https://www.espn.com.co/futbol/posiciones/_/li...
4     FRANCIA  https://www.espn.com.co/futbol/posiciones/_/li...
5    PORTUGAL  https://www.espn.com.co/futbol/posiciones/_/li...
6     HOLANDA  https://www.espn.com.co/futbol/posiciones/_/li...

In [48]:
df_ligas['URL'][1]

'https://www.espn.com.co/futbol/posiciones/_/liga/eng.1'

In [49]:
df = pd.read_html(df_ligas['URL'][0])

In [50]:
len(df)

2

In [51]:
df[0]

               2024/2025
0          1BARBarcelona
1        2MADReal Madrid
2    3ATLAtlético Madrid
3      4ATHAthletic Club
4         5VLRVillarreal
5         6BETReal Betis
6           7MLAMallorca
7         8VIGCelta Vigo
8     9RAYRayo Vallecano
9        10SEVSevilla FC
10           11GETGetafe
11    12SOCReal Sociedad
12           13GIRGirona
13          14OSAOsasuna
14         15ESPEspanyol
15         16VALValencia
16           17ALAAlavés
17      18LeganésLeganés
18       19PALLas Palmas
19  20VLDReal Valladolid

In [52]:
df[1]

     J   G   E   P  GF  GC  DIF  PTS
0   27  19   3   5  75  27   48   60
1   28  18   6   4  59  27   32   60
2   28  16   8   4  46  22   24   56
3   28  14  10   4  46  24   22   52
4   27  12   8   7  49  38   11   44
5   28  12   8   8  38  35    3   44
6   28  11   7  10  28  34   -6   40
7   28  11   6  11  41  41    0   39
8   28   9  10   9  31  31    0   37
9   28   9   9  10  32  37   -5   36
10  28   9   9  10  25  23    2   36
11  28  10   5  13  25  30   -5   35
12  28   9   7  12  36  41   -5   34
13  27   7  12   8  33  39   -6   33
14  27   7   7  13  26  39  -13   28
15  28   6  10  12  31  46  -15   28
16  28   6   9  13  32  42  -10   27
17  28   6   9  13  26  43  -17   27
18  28   6   7  15  32  47  -15   25
19  28   4   4  20  18  63  -45   16

In [53]:
df=pd.concat([df[0],df[1]],ignore_index=True,axis=1)
df

                       0   1   2   3   4   5   6   7   8
0          1BARBarcelona  27  19   3   5  75  27  48  60
1        2MADReal Madrid  28  18   6   4  59  27  32  60
2    3ATLAtlético Madrid  28  16   8   4  46  22  24  56
3      4ATHAthletic Club  28  14  10   4  46  24  22  52
4         5VLRVillarreal  27  12   8   7  49  38  11  44
5         6BETReal Betis  28  12   8   8  38  35   3  44
6           7MLAMallorca  28  11   7  10  28  34  -6  40
7         8VIGCelta Vigo  28  11   6  11  41  41   0  39
8     9RAYRayo Vallecano  28   9  10   9  31  31   0  37
9        10SEVSevilla FC  28   9   9  10  32  37  -5  36
10           11GETGetafe  28   9   9  10  25  23   2  36
11    12SOCReal Sociedad  28  10   5  13  25  30  -5  35
12           13GIRGirona  28   9   7  12  36  41  -5  34
13          14OSAOsasuna  27   7  12   8  33  39  -6  33
14         15ESPEspanyol  27   7   7  13  26  39 -13  28
15         16VALValencia  28   6  10  12  31  46 -15  28
16           17ALAAlavés  28   6   9  13  32  42 -10  27
17      18LeganésLeganés  28   6   9  13  26  43 -17  27
18       19PALLas Palmas  28   6   7  15  32  47 -15  25
19  20VLDReal Valladolid  28   4   4  20  18  63 -45  16

In [54]:
df=df.rename(columns={0:'EQUIPO',1:'J', 2:'G', 3:'E', 4:'P', 5:'GF', 6:'GC', 7:'DIF', 8:'PTS'})
df['EQUIPO']=df['EQUIPO'].apply(lambda x: x[5:] if x[:2].isnumeric()==True else x[4:])
df['LIGA'] = df_ligas['LIGA'][1]

In [55]:
df

             EQUIPO   J   G   E   P  GF  GC  DIF  PTS        LIGA
0         Barcelona  27  19   3   5  75  27   48   60  INGLATERRA
1       Real Madrid  28  18   6   4  59  27   32   60  INGLATERRA
2   Atlético Madrid  28  16   8   4  46  22   24   56  INGLATERRA
3     Athletic Club  28  14  10   4  46  24   22   52  INGLATERRA
4        Villarreal  27  12   8   7  49  38   11   44  INGLATERRA
5        Real Betis  28  12   8   8  38  35    3   44  INGLATERRA
6          Mallorca  28  11   7  10  28  34   -6   40  INGLATERRA
7        Celta Vigo  28  11   6  11  41  41    0   39  INGLATERRA
8    Rayo Vallecano  28   9  10   9  31  31    0   37  INGLATERRA
9        Sevilla FC  28   9   9  10  32  37   -5   36  INGLATERRA
10           Getafe  28   9   9  10  25  23    2   36  INGLATERRA
11    Real Sociedad  28  10   5  13  25  30   -5   35  INGLATERRA
12           Girona  28   9   7  12  36  41   -5   34  INGLATERRA
13          Osasuna  27   7  12   8  33  39   -6   33  INGLATERRA
14         Espanyol  27   7   7  13  26  39  -13   28  INGLATERRA
15         Valencia  28   6  10  12  31  46  -15   28  INGLATERRA
16           Alavés  28   6   9  13  32  42  -10   27  INGLATERRA
17      anésLeganés  28   6   9  13  26  43  -17   27  INGLATERRA
18       Las Palmas  28   6   7  15  32  47  -15   25  INGLATERRA
19  Real Valladolid  28   4   4  20  18  63  -45   16  INGLATERRA